# =============================================================================
# BASE CONFIGURATION
# =============================================================================

version: "3.7"

# =============================================================================
# SERVICES
# =============================================================================

services:

# =============================================================================
# SEARCH STRING
# =============================================================================

  search-string:
    container_name: ${CONTAINER_NAME}
    env_file: ./.env
    build:
      context: ./${PATH_DOCKERFILE}
      dockerfile: Dockerfile
    entrypoint: >
      /bin/sh -c "
        set -e
        echo -e "\nStarting...\n"
        /bin/bash || exit 0
      "
    restart: unless-stopped
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "20"
    networks:
      - search-string

# =============================================================================
# NETWORK
# =============================================================================

networks:
  search-string:
